# Generated by Django 4.1.1 on 2022-10-23 22:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='content',
            field=tinymce.models.HTMLField(default='asd'),
            preserve_default=False,
        ),
    ]
