# Generated by Django 4.1.1 on 2022-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='createdAt',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
    ]
