# Generated by Django 4.1.1 on 2022-10-08 16:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('description', models.TextField(max_length=350, verbose_name='Descripción')),
                ('content', tinymce.models.HTMLField()),
                ('thumbnail', models.URLField(max_length=510, verbose_name='Thumbnail')),
                ('status', models.BooleanField(default=False, verbose_name='Activado/Desactivado')),
                ('createdAt', models.DateTimeField(verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias',
                'ordering': ['-createdAt'],
            },
        ),
    ]
